#!/system/bin/sh

# **************************************************************
# Add Synapse support
# **************************************************************

UKM=/res/synapse;
BB=/sbin/bb/busybox;
UCI_CONFIG=$UKM/config.json;
DEBUG=$UKM/debug;
UCI_FILE=$UKM/uci;
UCI_SBIN=/system/sbin/uci;

# Delete known files that re-create uci config

#if [ -e "/data/ak/ak-post-boot.sh" ]; then
#	$BB rm -f /data/ak/ak-post-boot.sh #ak
#	$BB rm -f /sbin/post-init.sh #neobuddy89
#fi

# Delete default uci config in case kernel has one already to avoid duplicates.

if [ -e "/sbin/uci" ]; then
	$BB rm -f /sbin/uci
fi

# Delete all debug files so it can be re-created on boot.

$BB rm -f $DEBUG/*

# Reset profiles to default

$BB echo "Custom" > $UKM/files/gamma_prof
$BB echo "Custom" > $UKM/files/lmk_prof
$BB echo "Custom" > $UKM/files/sound_prof
$BB echo "Custom" > $UKM/files/speaker_prof
$BB echo "0" > $UKM/files/volt_prof;
$BB echo "0" > $UKM/files/dropcaches_prof;

# Symlink uci file to sbin in case it's not found.

if [ ! -e $UCI_SBIN ]; then
	$BB mount -o remount,rw /system
	$BB mount -t rootfs -o remount,rw rootfs
	
	$BB chmod 755 $UCI_FILE
	$BB ln -s $UCI_FILE $UCI_SBIN
	$BB chmod 755 $UCI_SBIN
	
	$BB mount -t rootfs -o remount,ro rootfs
	$BB mount -o remount,ro /system
fi

# If uci files does not have 755 permissions, set permissions.

if [ `$BB stat -c %a $UCI_FILE` -lt "755" ]; then
	$BB chmod 755 $UCI_FILE
fi

if [ `$BB stat -c %a $UCI_SBIN` -lt "755" ]; then
	$BB mount -o remount,rw /system
	$BB mount -t rootfs -o remount,rw rootfs
	$BB chmod 755 $UCI_SBIN
	$BB mount -t rootfs -o remount,ro rootfs
	$BB mount -o remount,ro /system
fi

# Reset uci config so it can be re-created on boot.

$UCI_SBIN reset;
$BB sleep 1;
$UCI_SBIN;
