cflags-y	+= -os

### HotPlugs ###
obj-y	:= msm_zen_decision.o msm_sleeper.o

obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_plug.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_MSM_ZEN_DECISION) += msm_zen_decision.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_MAKO_HOTPLUG) += mako_hotplug.o
obj-$(CONFIG_MSM_SLEEPER) += msm_sleeper.o
obj-$(CONFIG_AUTOSMP2) += autosmp2.o
obj-$(CONFIG_BLU_PLUG) += blu_plig.o
obj-$(CONFIG_FAST_HOTPLUG) += fast_hotplug.o
obj-$(CONFIG_MAKO_HOTPLUG) += mako_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o

