cflags-y	+= -o2

### HotPlugs ###
obj-y	:= intelli_plug.o bricked_hotplug.o msm_zen_decision.o alucard_hotplug.o msm_hotplug.o mako_hotplug.o

#obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
#obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o
#obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
